name: Django CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Heroku
      uses: akshatmittal/heroku-login-action@v1
      with:
        api_key: ${{ secrets.HEROKU_API_KEY }}

    - name: Set environment variables
      run: |
        heroku config:set SECRET_KEY=${{ secrets.SECRET_KEY }} \
                           DEBUG=${{ secrets.DEBUG }} \
                           MODE=${{ secrets.MODE }} \
                           DISABLE_COLLECTSTATIC=${{ secrets.DISABLE_COLLECTSTATIC }} \
                           AFRICASTALKING_API_KEY=${{ secrets.AFRICASTALKING_API_KEY }} \
                           DATABASE_URL=${{ secrets.DATABASE_URL }} \
                           --app tc4a

    - name: Deploy to Heroku
      run: git push heroku main

