name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework
        pip install -r requirements.txt
    - name: Load environment variables from .env
      run: |
        cp .env .env.local
    - name: Run tests
      env:
        MODE: 'prod'
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py migrate
        python manage.py test
